name: test

on:
  push:
  pull_request:
    branches: [main, beta]
  schedule:
    # run daily at 00:00
    - cron: 0 0 * * *

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        playwrightVersion: ['1.35', 'latest', 'beta']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm install @playwright/test@${{ matrix.playwrightVersion }}
      - run: npx playwright install --with-deps chromium
      - run: npm test
